describe("diffview.lib", function()
  local lib = require("diffview.lib")

  describe("make_reuse_key", function()
    it("produces the same key for identical arguments", function()
      local a = lib.make_reuse_key("HEAD", true, false, false)
      local b = lib.make_reuse_key("HEAD", true, false, false)
      assert.are.equal(a, b)
    end)

    it("differs when cached flag differs", function()
      local without = lib.make_reuse_key("HEAD", false, false, false)
      local with = lib.make_reuse_key("HEAD", true, false, false)
      assert.are_not.equal(without, with)
    end)

    it("differs when rev_arg differs", function()
      local a = lib.make_reuse_key("HEAD", false, false, false)
      local b = lib.make_reuse_key("HEAD~1", false, false, false)
      assert.are_not.equal(a, b)
    end)

    it("treats nil rev_arg as empty string", function()
      local a = lib.make_reuse_key(nil, false, false, false)
      local b = lib.make_reuse_key("", false, false, false)
      assert.are.equal(a, b)
    end)

    it("differs when imply_local flag differs", function()
      local without = lib.make_reuse_key(nil, false, false, false)
      local with = lib.make_reuse_key(nil, false, true, false)
      assert.are_not.equal(without, with)
    end)

    it("differs when merge_base flag differs", function()
      local without = lib.make_reuse_key("HEAD", false, false, false)
      local with = lib.make_reuse_key("HEAD", false, false, true)
      assert.are_not.equal(without, with)
    end)
  end)
end)
